package com.netflix.titus.common.model.validator;

/**
 * Validation errors are generated by {@link EntityValidator}s.  They indicate various reasons why a Job may be malformed.
 */
public class ValidationError {
    private final String field;
    private final String description;
    private final Type type;

    /**
     * The error type defined here is an indication of the seriousness of the error.  In general "HARD" errors should be
     * considered fatal, in that continued use of the validated object is not recommended.  SOFT errors indicate that
     * subsequent use of the validated object is possible.
     */
    public enum Type {
        HARD,
        SOFT
    }

    public ValidationError(String field, String description) {
        this(field, description, Type.HARD);
    }

    public ValidationError(String field, String description, Type type) {
        this.field = field;
        this.description = description;
        this.type = type;
    }

    public String getField() {
        return field;
    }

    public String getDescription() {
        return description;
    }

    public Type getType() {
        return type;
    }

    public String getMessage() {
        return String.format("field: '%s', description: '%s', type: '%s'", field, description, type);
    }

    public boolean isHard() {
        return getType().equals(Type.HARD);
    }

    public boolean isSoft() {
        return getType().equals(Type.SOFT);
    }

    @Override
    public String toString() {
        return String.format("Validation failed: '%s'", getMessage());
    }
}
