package com.netflix.titus.common.model.validator;

/**
 * Validation errors are generated by {@link Validator}s.  They indicate various reasons why a Job may be malformed.
 */
public class ValidationError {
    private final String msg;

    public ValidationError(String msg) {
        this.msg = msg;
    }

    public String getMessage() {
        return msg;
    }

    @Override
    public String toString() {
        return String.format("Validation failed: '%s'", msg);
    }
}
