apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: members.clustermembership.titus.netflix
spec:
  group: clustermembership.titus.netflix
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          properties:
            state:
              type: string
            enabled:
              type: boolean
            addresses:
              type: array
              items:
                type: object
                properties:
                  ipAddress:
                    type: string
            labels:
              type: properties
  scope: Namespaced
  names:
    plural: members
    singular: member
    kind: Members
    shortNames:
      - mbs
