apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: members.clustermembership.titus.netflix
spec:
  group: clustermembership.titus.netflix
  version: v1alpha1
  versions:
    - name: v1alpha1
      served: true
      storage: true
  scope: Namespaced
  names:
    plural: members
    singular: member
    kind: Members
    shortNames:
      - mbs
  preserveUnknownFields: true