// This file is autogenerated!!!
// DO NOT EDIT
//
// Instead make changes to titus-kube-common
// https://github.com/Netflix/titus-kube-common/blob/master/pod/annotations.go
// And then run make refresh in this directory
// 
package com.netflix.titus.common.kube;

public class Annotations {

	public static final String 	AnnotationKeyInstanceType = "node.titus.netflix.com/itype";
	public static final String 	AnnotationKeyRegion       = "node.titus.netflix.com/region";
	public static final String 	AnnotationKeyStack        = "node.titus.netflix.com/stack";
	public static final String 	AnnotationKeyAZ           = "failure-domain.beta.kubernetes.io/zone";

	// Pod Networking
	public static final String 	AnnotationKeyEgressBandwidth  = "kubernetes.io/egress-bandwidth";
	public static final String 	AnnotationKeyIngressBandwidth = "kubernetes.io/ingress-bandwidth";

	// Pod ENI
	// AnnotationKeyIPAddress represents a generic "primary", could be ipv4 or v6
	public static final String 	AnnotationKeyIPAddress        = "network.netflix.com/address-ip";
	public static final String 	AnnotationKeyIPv4Address      = "network.netflix.com/address-ipv4";
	public static final String 	AnnotationKeyIPv4PrefixLength = "network.netflix.com/prefixlen-ipv4";
	public static final String 	AnnotationKeyIPv6Address      = "network.netflix.com/address-ipv6";
	public static final String 	AnnotationKeyIPv6PrefixLength = "network.netflix.com/prefixlen-ipv6";
	// AnnotationKeyIPv4TransitionAddress represents the "NAT" ip for certain IPv6-only modes
	public static final String 	AnnotationKeyIPv4TransitionAddress = "network.netflix.com/address-transition-ipv4";
	public static final String 	AnnotationKeyElasticIPv4Address    = "network.netflix.com/address-elastic-ipv4";
	public static final String 	AnnotationKeyElasticIPv6Address    = "network.netflix.com/address-elastic-ipv6";

	public static final String 	AnnotationKeyBranchEniID     = "network.netflix.com/branch-eni-id";
	public static final String 	AnnotationKeyBranchEniMac    = "network.netflix.com/branch-eni-mac";
	public static final String 	AnnotationKeyBranchEniVpcID  = "network.netflix.com/branch-eni-vpc";
	public static final String 	AnnotationKeyBranchEniSubnet = "network.netflix.com/branch-eni-subnet";

	public static final String 	AnnotationKeyTrunkEniID    = "network.netflix.com/trunk-eni-id";
	public static final String 	AnnotationKeyTrunkEniMac   = "network.netflix.com/trunk-eni-mac";
	public static final String 	AnnotationKeyTrunkEniVpcID = "network.netflix.com/trunk-eni-vpc";

	public static final String 	AnnotationKeyVlanID        = "network.netflix.com/vlan-id";
	public static final String 	AnnotationKeyAllocationIdx = "network.netflix.com/allocation-idx";

	// Security

	// matches kube2iam
	public static final String 	AnnotationKeyIAMRole              = "iam.amazonaws.com/role";
	public static final String 	AnnotationKeySecurityGroupsLegacy = "network.titus.netflix.com/securityGroups";
	// https://kubernetes.io/docs/tutorials/clusters/apparmor/#securing-a-pod
	public static final String 	AnnotationKeyPrefixAppArmor = "container.apparmor.security.beta.kubernetes.io";

	//
	// v1 pod spec annotations
	//

	// AnnotationKeyPodSchemaVersion is an integer specifying what schema version a pod was created with
	public static final String 	AnnotationKeyPodSchemaVersion = "pod.netflix.com/pod-schema-version";

	// Workload-specific fields

	public static final String 	AnnotationKeyWorkloadDetail     = "workload.netflix.com/detail";
	public static final String 	AnnotationKeyWorkloadName       = "workload.netflix.com/name";
	public static final String 	AnnotationKeyWorkloadOwnerEmail = "workload.netflix.com/owner-email";
	public static final String 	AnnotationKeyWorkloadSequence   = "workload.netflix.com/sequence";
	public static final String 	AnnotationKeyWorkloadStack      = "workload.netflix.com/stack";

	// Titus-specific fields

	public static final String 	AnnotationKeyJobAcceptedTimestampMs = "v3.job.titus.netflix.com/accepted-timestamp-ms";
	public static final String 	AnnotationKeyJobID                  = "v3.job.titus.netflix.com/id";
	public static final String 	AnnotationKeyJobType                = "v3.job.titus.netflix.com/type";
	public static final String 	AnnotationKeyJobDescriptor          = "v3.job.titus.netflix.com/descriptor";
	// AnnotationKeyPodTitusContainerInfo - to be removed once VK supports the full pod spec
	public static final String 	AnnotationKeyPodTitusContainerInfo = "pod.titus.netflix.com/container-info";
	// AnnotationKeyPodTitusEntrypointShellSplitting tells the executor to preserve the legacy shell splitting behaviour
	public static final String 	AnnotationKeyPodTitusEntrypointShellSplitting = "pod.titus.netflix.com/entrypoint-shell-splitting-enabled";
	// AnnotationKeyPodTitusSystemEnvVarNames tells the executor the names of the system-specified environment variables
	public static final String 	AnnotationKeyPodTitusSystemEnvVarNames = "pod.titus.netflix.com/system-env-var-names";
	// AnnotationKeyPodInjectedEnvVarNames tells the executor the names of the externally-injected environment variables,
	// which neither come from the user nor titus itself, and should be ignored for identify verification purposes
	public static final String 	AnnotationKeyPodInjectedEnvVarNames = "pod.titus.netflix.com/injected-env-var-names";
	// AnnotationKeyImageTagPrefix stores the original tag for the an image.
	// This is because on the v1 pod image field, there is only room for the digest and no room for the tag it came from
	public static final String 	AnnotationKeyImageTagPrefix = "pod.titus.netflix.com/image-tag-";

	// networking - used by the Titus CNI
	public static final String 	AnnotationKeySubnetsLegacy             = "network.titus.netflix.com/subnets";
	public static final String 	AnnotationKeyAccountIDLegacy           = "network.titus.netflix.com/accountId";
	public static final String 	AnnotationKeyNetworkAccountID          = "network.netflix.com/account-id";
	public static final String 	AnnotationKeyNetworkBurstingEnabled    = "network.netflix.com/network-bursting-enabled";
	public static final String 	AnnotationKeyNetworkAssignIPv6Address  = "network.netflix.com/assign-ipv6-address";
	public static final String 	AnnotationKeyNetworkElasticIPPool      = "network.netflix.com/elastic-ip-pool";
	public static final String 	AnnotationKeyNetworkElasticIPs         = "network.netflix.com/elastic-ips";
	public static final String 	AnnotationKeyNetworkIMDSRequireToken   = "network.netflix.com/imds-require-token";
	public static final String 	AnnotationKeyNetworkJumboFramesEnabled = "network.netflix.com/jumbo-frames-enabled";
	public static final String 	AnnotationKeyNetworkMode               = "network.netflix.com/network-mode";
	// AnnotationKeyEffectiveNetworkMode represents the network mode computed by the titus-executor
	// This may not be the same as the original (potentially unset) requested network mode
	public static final String 	AnnotationKeyEffectiveNetworkMode  = "network.netflix.com/effective-network-mode";
	public static final String 	AnnotationKeyNetworkSecurityGroups = "network.netflix.com/security-groups";
	public static final String 	AnnotationKeyNetworkSubnetIDs      = "network.netflix.com/subnet-ids";
	// TODO: deprecate this in favor of using the UUID annotation below
	public static final String 	AnnotationKeyNetworkStaticIPAllocationUUID = "network.netflix.com/static-ip-allocation-uuid";

	// storage
	public static final String 	AnnotationKeyStorageEBSVolumeID  = "ebs.volume.netflix.com/volume-id";
	public static final String 	AnnotationKeyStorageEBSMountPath = "ebs.volume.netflix.com/mount-path";
	public static final String 	AnnotationKeyStorageEBSMountPerm = "ebs.volume.netflix.com/mount-perm";
	public static final String 	AnnotationKeyStorageEBSFSType    = "ebs.volume.netflix.com/fs-type";

	// security

	public static final String 	AnnotationKeySecurityWorkloadMetadata    = "security.netflix.com/workload-metadata";
	public static final String 	AnnotationKeySecurityWorkloadMetadataSig = "security.netflix.com/workload-metadata-sig";

	// opportunistic resources (see control-plane and scheduler code)

	// AnnotationKeyOpportunisticCPU - assigned opportunistic CPUs
	public static final String 	AnnotationKeyOpportunisticCPU = "opportunistic.scheduler.titus.netflix.com/cpu";
	// AnnotationKeyOpportunisticResourceID - name of the opportunistic resource CRD used during scheduling
	public static final String 	AnnotationKeyOpportunisticResourceID = "opportunistic.scheduler.titus.netflix.com/id";

	// AnnotationKeyPredictionRuntime - predicted runtime (Go’s time.Duration format)
	public static final String 	AnnotationKeyPredictionRuntime = "predictions.scheduler.titus.netflix.com/runtime";
	// AnnotationKeyPredictionConfidence - confidence (percentile) of the prediction picked above
	public static final String 	AnnotationKeyPredictionConfidence = "predictions.scheduler.titus.netflix.com/confidence";
	// AnnotationKeyPredictionModelID - model uuid used for the runtime prediction picked above
	public static final String 	AnnotationKeyPredictionModelID = "predictions.scheduler.titus.netflix.com/model-id";
	// AnnotationKeyPredictionModelVersion - version of the model used for the prediction above
	public static final String 	AnnotationKeyPredictionModelVersion = "predictions.scheduler.titus.netflix.com/version";

	// AnnotationKeyPredictionABTestCell - cell allocation for prediction AB tests
	public static final String 	AnnotationKeyPredictionABTestCell = "predictions.scheduler.titus.netflix.com/ab-test";
	// AnnotationKeyPredictionPredictionAvailable - array of predictions available during job admission
	public static final String 	AnnotationKeyPredictionPredictionAvailable = "predictions.scheduler.titus.netflix.com/available";
	// AnnotationKeyPredictionSelectorInfo - metadata from the prediction selection algorithm
	public static final String 	AnnotationKeyPredictionSelectorInfo = "predictions.scheduler.titus.netflix.com/selector-info";

	// pod features

	public static final String 	AnnotationKeyPodCPUBurstingEnabled      = "pod.netflix.com/cpu-bursting-enabled";
	public static final String 	AnnotationKeyPodKvmEnabled              = "pod.netflix.com/kvm-enabled";
	public static final String 	AnnotationKeyPodFuseEnabled             = "pod.netflix.com/fuse-enabled";
	public static final String 	AnnotationKeyPodHostnameStyle           = "pod.netflix.com/hostname-style";
	public static final String 	AnnotationKeyPodOomScoreAdj             = "pod.netflix.com/oom-score-adj";
	public static final String 	AnnotationKeyPodSchedPolicy             = "pod.netflix.com/sched-policy";
	public static final String 	AnnotationKeyPodSeccompAgentNetEnabled  = "pod.netflix.com/seccomp-agent-net-enabled";
	public static final String 	AnnotationKeyPodSeccompAgentPerfEnabled = "pod.netflix.com/seccomp-agent-perf-enabled";
	public static final String 	AnnotationKeyPodTrafficSteeringEnabled  = "pod.netflix.com/traffic-steering-enabled";

	// container annotations (specified on a pod about a container)
	// Specific containers indicate they want to set something by appending
	// a prefix key with their container name ($name.containers.netflix.com).
	public static final String 	AnnotationKeySuffixContainers        = "containers.netflix.com";
	public static final String 	AnnotationKeySuffixContainersSidecar = "platform-sidecar";

	// logging config

	public static final String 	AnnotationKeyLogKeepLocalFile       = "log.netflix.com/keep-local-file-after-upload";
	public static final String 	AnnotationKeyLogS3BucketName        = "log.netflix.com/s3-bucket-name";
	public static final String 	AnnotationKeyLogS3PathPrefix        = "log.netflix.com/s3-path-prefix";
	public static final String 	AnnotationKeyLogS3WriterIAMRole     = "log.netflix.com/s3-writer-iam-role";
	public static final String 	AnnotationKeyLogStdioCheckInterval  = "log.netflix.com/stdio-check-interval";
	public static final String 	AnnotationKeyLogUploadThresholdTime = "log.netflix.com/upload-threshold-time";
	public static final String 	AnnotationKeyLogUploadCheckInterval = "log.netflix.com/upload-check-interval";
	public static final String 	AnnotationKeyLogUploadRegexp        = "log.netflix.com/upload-regexp";

	// service configuration

	public static final String 	AnnotationKeyServicePrefix = "service.netflix.com";

	// sidecar configuration

	public static final String 	AnnotationKeySuffixSidecars                      = "platform-sidecars.netflix.com";
	public static final String 	AnnotationKeySuffixSidecarsChannelOverride       = "channel-override";
	public static final String 	AnnotationKeySuffixSidecarsChannelOverrideReason = "channel-override-reason";
	// release = $channel/$version
	public static final String 	AnnotationKeySuffixSidecarsRelease = "release";

	// scheduling soft SLAs
	// priority handling in scheduling queue
	public static final String 	AnnotationKeySchedLatencyReq   = "scheduler.titus.netflix.com/sched-latency-req";
	public static final String 	AnnotationValSchedLatencyDelay = "delay";
	public static final String 	AnnotationValSchedLatencyFast  = "fast";
	// dynamic spreading behavior
	public static final String 	AnnotationKeySchedSpreadingReq    = "scheduler.titus.netflix.com/spreading-req";
	public static final String 	AnnotationValSchedSpreadingPack   = "pack";
	public static final String 	AnnotationValSchedSpreadingSpread = "spread";
}
