#!/bin/bash

set -eu -o pipefail

ci=${CI:-false}
tag=${CIRCLE_TAG:-}

if ! [[ "$ci" == true && -n "$tag" ]]; then
  echo "$0 must run in a CI environent" >&2
  exit 1
fi

case "$tag" in
*-rc\.*)
  ./gradlew -Prelease.useLastTag=true -PbintrayUser="${bintrayUser:-}" -PbintrayKey="${bintrayKey:-}" \
    -PsonatypeUsername="${sonatypeUsername:-}" -PsonatypePassword="${sonatypePassword:-}" candidate --stacktrace
  ;;
*)
  ./gradlew -Prelease.useLastTag=true -PbintrayUser="${bintrayUser:-}" -PbintrayKey="${bintrayKey:-}" \
    -PsonatypeUsername="${sonatypeUsername:-}" -PsonatypePassword="${sonatypePassword:-}" final --stacktrace
  ;;
esac

