FROM titusoss/titus-agent

RUN echo "deb http://repos.mesosphere.io/ubuntu xenial main" > /etc/apt/sources.list.d/mesosphere.list
RUN apt-key adv --keyserver keyserver.ubuntu.com --recv E56151BF

# TODO: temporary workaround to avoid trying to fetch legacy docker package info, this will be fixed by the switch to k8s
RUN rm -f /etc/apt/sources.list.d/docker.list

RUN apt-get -y update
RUN DEBIAN_FRONTEND=noninteractive apt-get -qy --no-install-recommends install \
    jq mesos=1.1.3-2.0.1
RUN systemctl enable mesos-slave
RUN systemctl disable titus-setup-networking.service
RUN systemctl disable titus-vpc-gc.service
RUN systemctl disable titus-vpc-gc.timer

RUN mkdir -p /tmp/titus-executor/logs
RUN mkdir -p /lib/systemd/system/mesos-slave.service.d
COPY 10-mesos-env.conf /lib/systemd/system/mesos-slave.service.d/
COPY 10-disable-metadata-proxy.conf /lib/systemd/system/titus-metadata-proxy@.service.d/10-disable-metadata-proxy.conf
COPY mesos-env /usr/local/bin/mesos-env
RUN chmod +x /usr/local/bin/mesos-env
COPY titus-executor-wrapper /usr/local/bin/titus-executor-wrapper
RUN chmod +x /usr/local/bin/titus-executor-wrapper
