#!/bin/bash

set -eu -o pipefail

export METATRON_ENABLED=false
export DISABLE_GPU=true
export DISABLE_METRICS=true
export SHORT_CIRCUIT_QUITELITE=true
export USE_NEW_NETWORK_DRIVER=false
export DEBUG=true

exec /apps/titus-executor/bin/titus-executor --copy-uploader /tmp/titus-executor/logs
