#!/bin/bash
# Used as the script step on Travis

if [ "$TITUS_TEST_GROUP" == "integrationExcludeMaster" ]; then
  echo -e "Running integration tests (PR=$TRAVIS_PULL_REQUEST) => Branch [$TRAVIS_BRANCH]"
  ./gradlew -PintegrationTestScope=excludeMaster integrationTest --parallel --stacktrace
elif [ "$TITUS_TEST_GROUP" == "integrationOnlyMaster1" ]; then
  echo -e "Running integration tests (PR=$TRAVIS_PULL_REQUEST) => Branch [$TRAVIS_BRANCH]"
  ./gradlew -PintegrationTestScope=onlyMaster1 integrationTest --parallel --stacktrace
elif [ "$TITUS_TEST_GROUP" == "integrationOnlyMaster2" ]; then
  echo -e "Running integration tests (PR=$TRAVIS_PULL_REQUEST) => Branch [$TRAVIS_BRANCH]"
  ./gradlew -PintegrationTestScope=onlyMaster2 integrationTest --parallel --stacktrace
elif [ "$TITUS_TEST_GROUP" == "integrationOnlyMaster3" ]; then
  echo -e "Running integration tests (PR=$TRAVIS_PULL_REQUEST) => Branch [$TRAVIS_BRANCH]"
  ./gradlew -PintegrationTestScope=onlyMaster3 integrationTest --parallel --stacktrace
elif [ "$TITUS_TEST_GROUP" == "integrationNotParallelizable" ]; then
  echo -e "Running integration tests (PR=$TRAVIS_PULL_REQUEST) => Branch [$TRAVIS_BRANCH]"
  ./gradlew integrationNotParallelizableTest --parallel --stacktrace
elif [ "$TRAVIS_PULL_REQUEST" != "false" ]; then
  echo -e "Build Pull Request #$TRAVIS_PULL_REQUEST => Branch [$TRAVIS_BRANCH]"
  ./gradlew build --stacktrace
elif [ "$TRAVIS_PULL_REQUEST" == "false" ] && [ "$TRAVIS_TAG" == "" ]; then
  echo -e 'Build Branch with Snapshot => Branch ['$TRAVIS_BRANCH']'
  ./gradlew -Prelease.travisci=true build --stacktrace
elif [ "$TRAVIS_PULL_REQUEST" == "false" ] && [ "$TRAVIS_TAG" != "" ]; then
  echo -e 'Build Branch for Release => Branch ['$TRAVIS_BRANCH']  Tag ['$TRAVIS_TAG']'
  case "$TRAVIS_TAG" in
  *-rc\.*)
    ./gradlew -Prelease.travisci=true -Prelease.useLastTag=true -PbintrayUser="${bintrayUser}" -PbintrayKey="${bintrayKey}" -PsonatypeUsername="${sonatypeUsername}" -PsonatypePassword="${sonatypePassword}" candidate --stacktrace
    ;;
  *)
    ./gradlew -Prelease.travisci=true -Prelease.useLastTag=true -PbintrayUser="${bintrayUser}" -PbintrayKey="${bintrayKey}" -PsonatypeUsername="${sonatypeUsername}" -PsonatypePassword="${sonatypePassword}" final --stacktrace
    ;;
  esac
else
  echo -e 'WARN: Should not be here => Branch ['$TRAVIS_BRANCH']  Tag ['$TRAVIS_TAG']  Pull Request ['$TRAVIS_PULL_REQUEST']'
  ./gradlew build --stacktrace
fi
