#!/bin/bash

set -eu -o pipefail

# Can be used to update dependencies locked by dependency.lock files in various subprojects.
#
# Typically this is executed periodically by a bot in a CI environment, but it can be useful lock dependencies and pick
# new versions as part of a PR, so changes can be built/published before being merged into master.

./gradlew generateLock saveLock -PdependencyLock.includeTransitives=true -Pstatus=release

